import { ActionLink, Eyebrow, Headline, PageShell, Reveal } from "@/components/SitePrimitives";
import { ArrowRight } from "lucide-react";

export default function Developers() {
  const docs = ["Quickstart", "SDKs", "Interaction Events", "Context API", "Provider Connectors", "Intent Schema", "Webhooks", "Security", "Deployment", "Examples"];
  const values = [["Integrate once", "One SDK for interaction events."], ["Normalize everything", "Consistent schemas across providers."], ["Choose your stack", "Bring your existing AI and perception technologies."], ["Deploy your way", "Cloud, edge, local, or hybrid."]];
  return <PageShell>
    <section className="page-head"><div className="section-inner"><Reveal className="section-header"><Eyebrow>Developers</Eyebrow><Headline as="h1" first="Natural interaction." second="One integration." /><p>Build voice, gaze, gesture, touch, pen, sign, and contextual interaction into your application through a unified developer layer.</p><div className="action-row"><ActionLink href="/developers">Read the Docs</ActionLink><ActionLink href="/company/contact" secondary>Get API Key</ActionLink></div></Reveal></div></section>
    <section className="section"><div className="section-inner"><div className="value-grid">{values.map(([title, description], index) => <Reveal delay={index * 55} key={title}><article className="feature-card"><h3>{title}</h3><p>{description}</p></article></Reveal>)}</div></div></section>
    <section className="section api-dark"><div className="section-inner code-split"><Reveal><Eyebrow>Interaction events</Eyebrow><Headline as="h2" dark first="A single, predictable" second="event shape." /><p>Every modality is normalized into an event your application can consume without special cases.</p></Reveal><Reveal delay={100}><div className="code-window"><div className="code-window-top"><span className="window-dots"><i /><i /><i /></span><span>intent.json</span></div><pre><code>{"{"}{"\n  "}<span className="kw">"intent"</span>: <span className="str">"select"</span>,{"\n  "}<span className="kw">"target"</span>: {'{'}{"\n    "}<span className="kw">"type"</span>: <span className="str">"ui_object"</span>,{"\n    "}<span className="kw">"id"</span>: <span className="str">"product_428"</span>{"\n  "}{'}'}, {"\n  "}<span className="kw">"modalities"</span>: [{"\n    "}<span className="str">"gaze"</span>, <span className="str">"gesture"</span>, <span className="str">"voice"</span>{"\n  "}],{"\n  "}<span className="kw">"confidence"</span>: <span className="fn">0.97</span>{"\n"}{"}"}</code></pre></div></Reveal></div></section>
    <section className="section section-warm"><div className="section-inner"><Reveal className="section-header"><Eyebrow>Documentation</Eyebrow><Headline as="h2" first="Everything you need" second="to start building." /></Reveal><Reveal className="docs-list">{docs.map(title => <a href="#docs" key={title}>{title}<ArrowRight size={17} /></a>)}</Reveal></div></section>
  </PageShell>;
}
