import { ArchitectureDiagram, Eyebrow, Headline, PageShell, Reveal } from "@/components/SitePrimitives";

export default function Product() {
  const providers = ["Speech provider.", "Gaze technology.", "Hand tracking system.", "Vision models.", "Digital ink engine.", "Sign language system.", "Foundation model."];
  return <PageShell>
    <section className="page-head"><div className="section-inner"><Reveal className="section-header"><Eyebrow>Product</Eyebrow><Headline as="h1" first="One infrastructure layer" second="for human interaction." /><p>Connect the technologies that perceive human behavior and turn their outputs into structured intent your application can use.</p></Reveal></div></section>
    <section className="section section-dark"><div className="section-inner"><Reveal className="section-header"><Eyebrow>Architecture</Eyebrow><Headline as="h2" dark first="The interaction engine," second="made legible." /></Reveal><Reveal delay={90}><ArchitectureDiagram /></Reveal></div></section>
    <section className="section"><div className="section-inner"><Reveal className="section-header"><Eyebrow>Beyond signals</Eyebrow><Headline as="h2" first="Understand more than" second="individual signals." /><p>Raw signals tell you what happened. Creaovation helps determine what those signals mean together.</p></Reveal><Reveal><div className="compare-grid"><div className="compare-list"><p>RAW</p>{["Gaze coordinates.", "Voice transcript.", "Gesture coordinates.", "Pen stroke."].map(item => <span key={item}>{item}</span>)}</div><div className="compare-arrow">→</div><div className="compare-list compare-list-right"><p>CREAOVATION</p>{["Target.", "Intent.", "Relationship.", "Context.", "Confidence."].map(item => <span key={item}>{item}</span>)}</div></div></Reveal></div></section>
    <section className="section section-warm"><div className="section-inner"><Reveal className="section-header"><Eyebrow>Provider abstraction</Eyebrow><Headline as="h2" first="Use the best technology" second="for every modality." /><p>Creaovation is designed to sit above perception providers.</p></Reveal><Reveal><p className="about-lede" style={{fontSize: "18px", marginBottom: "19px"}}>Choose your preferred:</p><div className="provider-list">{providers.map(item => <span key={item}>{item}</span>)}</div><p style={{marginTop: "26px", color: "var(--muted)", fontSize: "17px"}}>Change providers later without rebuilding your application interaction logic.</p></Reveal></div></section>
    <section className="section section-dark"><div className="section-inner"><Reveal className="section-header"><Eyebrow>Reference resolution</Eyebrow><Headline as="h2" dark first={<>Give meaning to <mark>“this,” “that,”</mark></>} second="and “there.”" /><p>Human communication depends heavily on context. Creaovation combines interaction history, application state, visual information, gaze, gesture, and language to determine what a person is referring to.</p></Reveal><Reveal className="reference-examples" delay={80}><p>That enables interactions like:</p>{[<>“Open <mark>that</mark>.”</>, <>“Move <mark>this</mark> <mark>there</mark>.”</>, <>“Compare <mark>these two</mark>.”</>, <>“Use the <mark>one</mark> I circled.”</>, <>“Tell me why <mark>that</mark> is flashing.”</>].map((example, index) => <blockquote key={index}>{example}</blockquote>)}</Reveal></div></section>
  </PageShell>;
}
